language: en
reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 5
    drafts: false
    base_branches:
      - main
      - master
  poem: false
  collapse_walkthrough: false
chat:
  auto_reply: true
